#%RAML 1.0 DataType
type: string
enum:
  - Moon Landing
  - Flyby
  - Press Event
  - Docking
  - Undocking
  - Landing
  - Launch
  - Rehearsal
  - Relocation
  - Release
  - Celestial Event  
  - Unknown
  - EVA
  - Berthing
  - Static Fire
  - Spacecraft Event
  - Abort Test
  - Hatch Opening
  - Test Flight
  - Change of Command
  - Orbital Insertion
  - Farewell Ceremony
  - Ambient Pressure Test
  - Cryoproof Test
  - Wet Dress Rehearsal