#%RAML 1.0 DataType
type: object

properties:
  id: integer
  name: string
  date: datetime
  location: string
  type: string
  description: string
  url: string
  news_url: string
  video_url: string
  feature_image: string